---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    configInline:
      address-pools:
      - name: reserved  # Reserved single IP for DNS
        protocol: layer2
        auto-assign: false
        addresses:
        - 10.0.40.1/32
      - name: default
        protocol: layer2
        addresses:
        - 10.0.40.2-10.0.40.50
