---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-device-plugin
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: intel-charts
        namespace: flux-system
  values:
    name: intel-gpu-plugin
    nodeFeatureRule: true
