# Per-App Static PVs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexmediaserver-config-pv
  namespace: default
spec:
  storageClassName: local-ultrapool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/plexmediaserver-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - teslatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexmediaserver-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ultrapool
  volumeName: plexmediaserver-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexmediaserver-transcode-pv
  namespace: default
spec:
  storageClassName: local-ultrapool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/plexmediaserver-transcode
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - teslatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexmediaserver-transcode
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ultrapool
  volumeName: plexmediaserver-transcode-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-config-pv
  namespace: default
spec:
  storageClassName: local-ultrapool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/syncthing-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - teslatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ultrapool
  volumeName: syncthing-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tautulli-config-pv
  namespace: default
spec:
  storageClassName: local-ultrapool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/tautulli-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - teslatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ultrapool
  volumeName: tautulli-config-pv
  resources:
    requests:
      storage: 1Mi
