apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: kube-system
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:u3kJeyN31rhmzoldFE22uqroyXPgOvzFBuPh9n4oFs4qwqN+9dPM6KEX4o5dj79UfCQQUzxDQl0=,iv:EQMudrgKlynBHji+BTVWY5ye/z0QyQsLbJMI3x2XUF0=,tag:w33Aq/SLLYYm0owfW4XBdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-02T20:03:52Z"
    mac: ENC[AES256_GCM,data:wxrX7STDHq8qrQp5/QTYqSIRMgfkP5qMDN7AaGVeXm1WrSMUOon8OT26GGsmpNTHDqQC1p+T1NPE9LmV2ZFwS5xb4yYYlpuqrIMzgpnGUI3afKEX/SsMOmdoUVkE2uYY0w9C8R0YYAcspYRXMkdSJHKkZ5xW5EPfcsH0kyg+vKQ=,iv:xdPsfL9ouEne6dgkKOoBfEjKxHY4EvxkcNcAtUgeWHQ=,tag:DPAH0G3/4F1pHLbPzgQV1g==,type:str]
    pgp:
        - created_at: "2024-04-02T20:03:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz9mLsS3VhyQARAAgMN2c5Md0f4zj0uyma/RUC0dEiimOVL0uE2nCM34hvwI
            a6eLryNv/YDW+kXjrYyh7o3g1DIB5YUhA1/4gs4Foalvt1yPD/wXGOP/9vcWHbW/
            XL8JaKA66AUzStduNHrVbGcUPBtGOtlw1131hjxkRDB+objcDG02VbDNeDNqrGgB
            IAvotfemBiVjDYLRWN3BwrKo3eWUodgmP5A+cJxGU+S55vV82g5XaiHtCq54mZ23
            eo2zoZeNvpvOS/BAycfdl1qQdKvwyWZX0J1ohbrJRvRE/5MsZxHP7/Gi8j2iDz0w
            l4gavl7eqP75uhNblGjjAmNB9/xpJAMtjmK+770ee93Vicg1zBXF7TXAN+eOrA4j
            9cdGZwTZIm6BWHlrvG2vKzbC79ZC3O6DQo7o+Eu/7rGTuKYBwkHh2UiCjxcYDw7Y
            duq9vptdhCRBhvjY8QrDSJFhDIKh8pGWXPrBkNiIffbTGfPSkPgfRJXJ3h1CA/0I
            1uXjVNZmvqI9aKsajXMYdmQMtCqCyuvVagDZfcwAbRIeyqdrFzXZRdOYVA9PTAPB
            kMV8K+acWxD/uX1ifSobwEGMt/7pWk18IUPvDC+1YHBR9tPal8YJL3ygQLJdtjsk
            xAB8lduzW4U3qZEq9IpMB14RzsvF9KHJ4mVoxA4MTd/F1CYQCwVpYY4Ow/NVKrPU
            aAEJAhBhB52F2/GNiMNPLANfeKI7SI6zHsoBbN5y/KxOP09ZE4DEtHa+BhfgcI4s
            QUGJgEOTYw+WkURIopttzGod3ERxJp192+KXvsF4Wk7cG5HD+RoGzy20IlI9p00M
            ICpv/496K2oO
            =3fdw
            -----END PGP MESSAGE-----
          fp: B85775F4E6689BDBD38DE156A1A31EE9E49F50E5
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
