---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  values:
    controllers:
      main:
        containers:
          main:
            envFrom:
              - secretRef:
                  name: frigate-secret
    persistence:
      config:
        existingClaim: frigate-config
        type: null
        accessMode: null
        size: null
      config-file:
        type: configMap
        name: frigate-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      media:
        existingClaim: frigate-media-pvc
        type: null
        accessMode: null
        size: null
