---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  values:
    controllers:
      main:
        containers:
          main:
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: 5000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 30
              readiness: *probes
    persistence:
      config:
        existingClaim: frigate-config
        type: null
        accessMode: null
        size: null
      media:
        existingClaim: frigate-media-pvc
        type: null
        accessMode: null
        size: null
