---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-data-pv
  namespace: default
spec:
  storageClassName: local-data
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/frigate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - deltapi5
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-data
  volumeName: frigate-data-pv
  resources:
    requests:
      storage: 1Mi
