apiVersion: v1
kind: Secret
metadata:
    name: frigate-env-secret
    namespace: default
type: opaque
data:
    LEGACY_CAM_PASS: ENC[AES256_GCM,data:TwU1RmQ62aBBltc3,iv:ZnAOVwJCjlrQzh8OPMrAWHI6n9GCY7F5TReNKj7gJSI=,tag:TM3P2OTnBVRvaQt4AyHoMg==,type:str]
    MQTT_USER: ENC[AES256_GCM,data:SnOrzhYC0Mt7HWNXCMB6vQ==,iv:Wii245o8m86Y0WYmbhyb7J3LDQQIx1gQUBS/4OKl1H0=,tag:vr/InydYRMBfQVVF64mCsg==,type:str]
    MQTT_PASS: ENC[AES256_GCM,data:uFft2DmOepLpvH/oaH4Q6ISkQuk6X6m/9cEXJQ==,iv:48su00nz9jaDiAm23qVv6s/dmTTF801U2JfL6l8Bb8c=,tag:jWnZdpVI1d+woaQzpqfcfw==,type:str]
    TAPO_CAM_USER: ENC[AES256_GCM,data:Z1LcXNH9Kvc=,iv:Xr4GOmFwMz4+4tiEDnLXKp5xqu9pIR8T4xt5WdE9dvE=,tag:UB7eQibSUXTql1K13+wJzg==,type:str]
    TAPO_CAM_PASS: ENC[AES256_GCM,data:+/6xur0AUshg1e+T0T0O6pYp+A1oUyCP4ZgcEg==,iv:/iz7yClxK5pEhMyyWYJyuKDN2QUnNEvXV4CfAUKYVjA=,tag:eLU0BNLJ1Ble5UbQAJ94Lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-03T19:55:05Z"
    mac: ENC[AES256_GCM,data:hWy/wqEaAGUd+s1u1DLVdXjvdAx4FZl3ZxYHGnOTSS8gdcHYI+rrlDsi+3ZAgGzEOkW53/K03tztqx/+db9j71bGNNz3YSHl4CZKzfiFIWycoYk0iTO1H6civQYd//yc4tOw7nXmXrWOVmE4vQwksA/6Asvn6BLwPeo1d2oOzW4=,iv:PM/7ZtOfCkor8zCmpwrzf1E64nvBh39XBWJM+42DTpY=,tag:7crHMy/tM/s+WRmFZ2z5RA==,type:str]
    pgp:
        - created_at: "2024-09-03T19:55:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwhYNqyBYBaDAQ/+JSs4hk+IBpmQ5e18YqxEUWDj7qapdDEkH5JBxgWPKO+7
            uTMqxjAifgpUHSi4bOo2ujPl1DEVwHsoa/VyzGH8S/BL7R3Ns2ESaOSu4RJyJBi3
            /cfsIgiEcIRkGvurKJ35YPzcdAVkjqDskGFoDt25U//sjRXdQI2TIygBpb2dqeEs
            5iVELdOXcYDHnsnpqboiGNN9/0OXOhK+YRH2pprMARp/MG1llIPTapRHcWxquTq1
            zQyaVxMJCqsjCRTu3CYy2EPl8qtY/UycETey0hLNAcUrqjBLmq5liYWTwOQi6c7+
            L12AwOrD2bVM+1CpIYOSNCIRSst04uFFUhukmWDXMZyeCP7+N7KEZn0J6BqObgRv
            VMM5+hvQDBlZD4EwWYCxULhs8lYzhHVidQ7oCdT6yU94EjGH4lsP5ubMutQidALR
            vFTXs6ZZUljCHNy3k3tedQdmPyjtv47Kc35g0nwKcbwHzoras+EmpSVOobpSVq3p
            Yfgps5+EHK45ZVYLyOjZpyqSFiHaCuo8jG4fUNqJoNTg2fQzeCNmNCcwR1Q95No1
            M54JVxxmZigJxKv74cxN/DBJw8n5yHgFiHx2GQMouDWnTB8ZxOh/Z2s5DC9kHCmV
            3QyJe/73GxSAuKrgaxl41VR+GihuqIf73fNsZHYL4/t4wLeZWr57JxMcI+VTowbU
            aAEJAhCm2l4etzKEEJDkt/Dq17sjLvMGAhDQQ44vqv1bQVdMM/QIlrBMnmPjbWop
            lXMm/HKWKErdhdEXJ1SrdpWDuvpcHuGiQwsYTc9h6Hb0cRJliDLVPnPmDh3xC6TR
            rnFn702iyFF3
            =P4aU
            -----END PGP MESSAGE-----
          fp: FD5A64001EA2E7BC91D0B02E726A1FDF8A155CBA
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
