---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: deluge
  namespace: default
spec:
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: gammatron
    persistence:
      downloads:
        existingClaim: downloads-pvc
        globalMounts:
          - path: /datapool/downloads
      config:
        existingClaim: deluge-config
        type: null
        accessMode: null
        size: null
    service:
      daemon:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_deluge}
        controller: main
        ports:
          torrents:
            port: 55066
            targetPort: 55066
            protocol: TCP
          admin:
            port: 58846
            targetPort: 58846
            protocol: TCP
