apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
data:
    address: ENC[AES256_GCM,data:FmWnG4yWiFuFrBj59canxy3/f33mr6vLXqsm4Jt5quwE0fJ3YLxV5qwLi+tROrvyMtCizRUFgUseFzEsRrYhPAt9QBl6TPbAGs6wgKBxviUK/8lnCV/Psu200uqJFsnRKWIwFhZ6DqcZu3YL09wybgUI7FYsBU7WbCU4qCBwdBYnmKTCAYaQtJjbt6VzNL9QOGho/1yjOp1LIfr/gIdnVzxFsFE=,iv:EGV/XiD1AuNCQ5gJY4o+biJHXIS4OBUyFmdby8jOjJ4=,tag:7BKwtNWe8U4LQF8flYt62Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-13T16:34:09Z"
    mac: ENC[AES256_GCM,data:muHw5wRanb5lD6bnEqvqjHKwvPjj/tURxLgn371hM6YMWGXkWslk/5AiiN4L9vp/jrSrMomVNw8aGxWGHTV+syIAqXxizcdC6EZKTpZjUOWUShkWmBVwqqNh71EYIly7ZaHgFjC8wHPkWYOUvisOi+0tk9YETJffb+KOzHfmDOo=,iv:ZPGPcql/LY1rOxNZ4uKTguu2HQ+8NO+CXxJ+8TwQhLs=,tag:o7qWukQ75KOJ6t35paNgDw==,type:str]
    pgp:
        - created_at: "2024-07-13T16:34:09Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwhYNqyBYBaDAQ/+O0lGv63zGJjzC3YN7u9A12fg1RLhdKooCi6BDKCCfuE+
            69KeJxE9ElpOgipEUCWhMKD6brejo04QQOj/OTqA56dqNJCG7JMfwjKetpi0JhWm
            /AQEBWUqeNcNc6IHDbwxviQH9/OyOWzVhyylFulY1TqmNt+38jPQ+lHW4qUuH7mP
            N0S7mcoLG30OekPvErTglGv+YQVHpeEBsJTMP6AFFi0CHshP62bATzKDlbJ2uxX4
            jSD8Qx/3Pg2fxPKMwndUg1PmtIdNRDGihNbsLIXdEQYY3OJ3zSUq/Cgq5RMvGItg
            gCn2fxGXFIob3vMu2tu0HDqAwxFHN0QLeiq4dcOX9+R66iOtkZ1qRjr0G5yplX4/
            J5kFPHmQhmmCxUD2XeoJ7uPd5XA3HSlbrGBqQpCn7c4pXAk88U7Yhr47gGGAXjZn
            lbR6NRWMjLCmEkR2oKyXXCaSTRFnX8JZ+3nGXntlNRaMuX3IBz5J2cGGbX/nF1Xy
            wKsBG4TENTihhiuTyIB+oc8nXzDW9pkj4JOMLXL+0Z91tdKlM6K/X1mZS8lHHGrg
            0KBEsySHaE+6MCyQO+DNGb8sqmJtPmwEOGMMV1SO/fYKyvpJm7+6d/x8639fRQeo
            YK0l+H/uPxeUFqWyu4M5Kwo3Jz1h9Z19RvwLXvTj5JdcbjseO52l8ETDTdYrANPU
            aAEJAhCwlVWdA6nr9mw0x9Nf/HfEqTD76/dJerZSsZypXH1iWyHnvdO/+oaxUqgo
            LhdPED+qom5ZVom8GCqouSiClN6ciFRramsVjo7BhuemlJTHTwY9/SOA5WiaXyyz
            KVn3sGu4w65C
            =LhY/
            -----END PGP MESSAGE-----
          fp: FD5A64001EA2E7BC91D0B02E726A1FDF8A155CBA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
