---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: gammatron
    persistence:
      videos:
        enabled: true
        readOnly: false
        existingClaim: videos-pvc
      downloads:
        enabled: true
        readOnly: false
        existingClaim: downloads-pvc
      config:
        existingClaim: sonarr-config
