---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
spec:
  values:
    persistence:
      config:
        existingClaim: tautulli-config
        type: null
        accessMode: null
        size: null
