---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- metallb-charts.yaml
- traefik-charts.yaml
- k8s-at-home-charts.yaml
- nfs-provisioner-charts.yaml
- jetstack-charts.yaml
- gitea-charts.yaml
- kubernetes-dashboard-charts.yaml