---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: default
spec:
  values:
    persistence:
      config:
        existingClaim: syncthing-config
      videos:
        enabled: true
        readOnly: false
        type: pvc
        existingClaim: videos-pvc
    service:
      main:
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_syncthing}
        enabled: true
        externalTrafficPolicy: Local
        type: LoadBalancer
        ports:
          sync:
            enabled: true
            port: 22000
            protocol: TCP
