# Per-App Static PVs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexmediaserver-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/plexmediaserver-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexmediaserver-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: plexmediaserver-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/deluge-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: deluge-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/syncthing-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: syncthing-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-influxdata-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/influxdb-influxdata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-influxdata
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: influxdb-influxdata-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ombi-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/ombi-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: ombi-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /${host_path_base}/grafana-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: grafana-config-pv
  resources:
    requests:
      storage: 5Gi
