# Per-App Static PVs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/radarr-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: radarr-config-pv
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/sonarr-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: sonarr-config-pv
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plexmediaserver-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/plexmediaserver-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plexmediaserver-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: plexmediaserver-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: deluge-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/deluge-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: deluge-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/syncthing-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: syncthing-config-pv
  resources:
    requests:
      storage: 1Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-controller-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/unifi-controller-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: unifi-controller-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-influxdata-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/influxdb-influxdata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-influxdata
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: influxdb-influxdata-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/homeassistant-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: homeassistant-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/prowlarr-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: prowlarr-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ombi-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/ombi-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: ombi-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tautulli-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/tautulli-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: tautulli-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/nextcloud-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: nextcloud-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datapool/nextcloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: nextcloud-data-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /${host_path_base}/grafana-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: grafana-config-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /${host_path_base}/audiobookshelf-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: audiobookshelf-config-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-metadata-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /${host_path_base}/audiobookshelf-metadata
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: audiobookshelf-metadata-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-media-pv
  namespace: default
spec:
  storageClassName: local-datapool
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datapool/audio
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-media
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-datapool
  volumeName: audiobookshelf-media-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: z2m-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/z2m-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: z2m-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: z2m-config-pv
  resources:
    requests:
      storage: 1Mi
