---
# PLex Production Patch
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: default
spec:
  values:
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: datapool-shared-config
        subPath: deluge-config
      videos:
        enabled: true
        readOnly: false
        existingClaim: videos-pvc
        mountPath: /datapool/videos
      downloads:
        enabled: true
        readOnly: false
        existingClaim: downloads-pvc
        mountPath: /datapool/downloads
    service:
      torrents:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_deluge}
        ports:
          torrent:
            enabled: true
            port: 55066
            targetPort: 55066
            protocol: TCP
