apiVersion: v1
kind: Secret
metadata:
    name: deluge-client-secret
    namespace: default
data:
    deluge-username: ENC[AES256_GCM,data:pDROiAWf8m8=,iv:VShb1+gemkZnApyxHaIoFeC84+fTqvnntfjvb19g6lM=,tag:Z7mcAKBtgwg7/RGU/vdfrg==,type:str]
    deluge-password: ENC[AES256_GCM,data:0w3QGn8+dEyyjFp4,iv:/OQITrgZ1PrnzKpiKl0yx6ZsSmvHI6aHUPlMwN9VAU8=,tag:m63/h4T3ff0SJO1tayElcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-13T21:51:13Z"
    mac: ENC[AES256_GCM,data:MDsIe2H4LMtgEfist4g7dudMe8IPy71Je3xDA14eufcZqoo+jIlWmng9kY4aER7+iOhvT98/1pY4sBKnRe2KDNN9vMX6hEGXeDGihG+LslkpYtKpMn3lMo5buEBT3Mt9O8B+YfGj/cvKspqkkL7SnBPY6Ct7tsmrabYDPeCZmMA=,iv:/PZ+QkfHhaJQ5gd3fNxFta+2qtmMJSLMFISS2TUeCZQ=,tag:VGPdxy+/MN/L7g+5as0mRw==,type:str]
    pgp:
        - created_at: "2023-03-13T21:51:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+yz/x7sIsGtAQ//Qlj1HXgsx+zwknNPM74k7Fq5FaU3YhExrUCx5CJthq9W
            b18B8ekTYFEMlyU6I7bGJJ+KeNTQR8RFMz21+vgXgapqtPW7P3lyrajLbu6yYDzt
            Y44vlTdvGihSvxwLtao7tXfZXjr5LQR8UcErACAxEDQ7f6ORQOinx7x/sw+WXxl4
            1z3SiBNpva8IWYQZGdVt1gTImfhvcPL3OJVG9ujfi72LoCt1s7Gt7k+/KO1jZgTA
            bI1KY+s6eEDDk/NvRdRR82WIAC76pfKo4Kc4GGaUeY+9Ii1qzWjKVv9uG+MLBFa4
            +MJjAgw+M76BIv7FwoTfWdYsaEf4TGcHemLUEKsLrjthlJR45xVoCj8gBQQxGILU
            J674l6jw26B3tk07lTrnQOFS1CLXhZzIyXM17xR4VHOOdvs4ql5a0O81/dnS3j9L
            usXeXeAe8u3PTZqkwG7jvFnFxOKyn4yQ27leJs4+GlD/py959qHFK8OQs/cJHY4A
            qKMcQDV5m83lcv98MRzhMehzXtlvUl7d7bimCeWNsvcHVb+meh0jM9GCJqUF/Xcl
            Ps6QnuTg1zKItyY/0WT1PVKpkoEbKe5SeQAD4F7hmGMVxrR+Pc8lk5O11AxiMJhG
            zAd/8wlLE1ri5INZHVLqUuvFr61/Yt99QSt77IYOD3aepGUnDsR5pOpFu717euvS
            XgG8kA9a2HlT1vmwAaGCoaUxrAXCIPBQBpf+8MJcpjydQZ53vPWg50k7sBRhB4jQ
            Tu2s7v0CddXBpWuWJ7qAjbGtUCcH9cB9cCUIvKYDNYFsX12R8A6uC8Cit471zVs=
            =Gek8
            -----END PGP MESSAGE-----
          fp: 4FBF8742DC108D1CBE41957BBD979CE0C5E0FE04
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
