apiVersion: v1
kind: Secret
metadata:
    name: github-garvbox-deploy
    namespace: default
data:
    .dockerconfigjson: ENC[AES256_GCM,data:mClTLvPLE5GaWnFsJh6+9pAx4IY6NCVZIM/LifUM839NiyIzBmXAZC9y+wb6AgyhntfwnqSS8V/pyOI4j/9lT5FQXXzPG987xHaH4FALMlzWnPZ5za9njp9KnI57Ok/EgwufRDvNUQJ4ZcrtLQIWUCsiAGW6Q8n2Gkp+vy018zWEikX5CjPGW8rF6shM42eRugCCd7wBYU0sY76DH1sBdmwx4/tIt9r1OgAbxSbN/t+briluQIyNmeBmL87u0PZZl0CKokPtySn4eE9ZF53Io7RzdhMch/om4+8fWleiyQQ+urOe6mJ94g==,iv:xOk6FJtFWn4owrGAj7tASnCiBKgLVshH7hWgw2fkeDs=,tag:SS/ivNC2K+GJ+gZ/owTpdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-02T20:31:33Z"
    mac: ENC[AES256_GCM,data:NYJRJaXxG0xVyj30WdMvQHu6NNBw3l+Wt1XzjeIKLILRP3XUeu1scS7tHrEPbG0bbOtfMJw7bjjsb7uoeTuAYYzMrov5LskdzA1QxMQYvR5uMYggha50Fdb1cyt2Lb+tyuhypaN+Rp1TBMAC9IjvJVKSLjcAqIIZAmTH1GLsLX4=,iv:AQORf1Xh+B7HD4wyb/cGzVb0tvkeve7cFFmEkPwKwAw=,tag:7CuiJOeiK2Sy93OP4o0lcQ==,type:str]
    pgp:
        - created_at: "2022-12-02T20:31:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+yz/x7sIsGtAQ/8DuHgm80TbMGG8pUPyHhSeUeQa8Jxb9jEsGtyzz+2eQkq
            tez+3m/sge3R2J3e4ItremfASTZJAcb3aNd8e49jvv/Iz8mMysalUJMTR2e29xxs
            ewIsRq5t+ZzjtLcOoJPCCMR6sOkfB8lIfxq/OnouoYKBAKq0kdkPyiHWDBZpc+oL
            hIGvdAQW5LrZSHzNAZl2LHEm46IqCY0GHwTlT6nKrnd/R8f+eYm3WKVDj+/1dk8B
            N9iCLhPoYC1IzT0BtwTQuQytX41PbPSc3scBFe2tVi2ymaQen3+Ag2hj//O/rLNA
            82C4tJA/RQsbLIV7fbDjbG7JSIm0eWqCMq4qTOw44GSTkgDeDvRTCRI5b/WRicBu
            dtCGDdo38j12uoVEF3ae8G+1ySFvq7BvvOyCGBb40JlMCee7zg+h++eQ9ANyIrIu
            ZjWMfNwuusNOR4go45A0ffar2o/tqGbmmy0zJFTBJ86hnAk48LQ6JTZrPVUIxkl8
            CqJ5X85+mcS+X3tviln6XYI6V2UBNyueLZyTTphE4bZ95ZzUiG5nurWeBFCZajt3
            0EIn+CEbEwjqZrHezVlEtNwkfFwmegUKApcRJbkpDlLF4UJ9+xLLtHb05U1P3V8s
            KPqHneTxrfiDJLqikItfa8806pzHDkQZN9YB3dWJ9xmMU+oxzs5oOvyhGQTGbazS
            XAF2+GQQnRqgqFJ0MoCwmd16YJDFk2HP+2TTKgOD4eMRd8Rvks6tl8iBb+5I/12L
            rRuDOZRnJe55FL3q5NCAppqelcnTgsp6CdXABKaLu5fUZrOupuGza4okTr83
            =Sow7
            -----END PGP MESSAGE-----
          fp: 4FBF8742DC108D1CBE41957BBD979CE0C5E0FE04
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
