---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  values:
    persistence:
      enabled: true
      type: pvc
      existingClaim: datapool-shared-config
      subPath: grafana-config
