
---
# HomeAssistant Prod NFS Patch for editable config
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  values:
    persistence:
      enabled: true
      type: pvc
      existingClaim: grafana-config-pvc
      size: 5Gi
