---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-external
  namespace: default
spec:
  ports:
    - name: homeassistant
      port: 8123
      protocol: TCP
      targetPort: 8123
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: homeassistant-external
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.0.12
    ports:
      - name: homeassistant
        port: 8123
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-external
  namespace: default
spec:
  rules:
    - host: homeassistant.${cluster_ext_domain}
      http:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: homeassistant-external
              port:
                number: 8123
