---
# Gammasite Production Apps
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ../base/sources
  - ../base/whoami.yaml
  - ../base/home-assistant.yaml
  - ../base/grafana.yaml
  - ../base/tautulli.yaml
  - ../base/jackett.yaml
  - ../base/radarr.yaml
  - ../base/sonarr.yaml
  - ../base/deluge.yaml
patchesStrategicMerge:
  - homeassistant-patch-values.yaml
  - grafana-patch-values.yaml
  - tautulli-patch-values.yaml
  - radarr-patch-values.yaml
  - sonarr-patch-values.yaml
