---
# Gammasite Production Apps
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gh-garvbox-secrets.yaml
  - ./config-vols.yaml
  - ./unpackerr/config-secret.yaml
  - ../sources
  - ../base/grafana.yaml
  - ../base/tautulli.yaml
  - ../base/jackett.yaml
  - ../base/radarr.yaml
  - ../base/sonarr.yaml
  - ../base/unpackerr.yaml
  - ../base/ombi.yaml
  - ../base/deluge.yaml
  - ../base/plexmediaserver.yaml
  - ../base/syncthing.yaml
  - ../base/unifi.yaml
  - ../base/homeassistant.yaml
  - ../base/mosquitto.yaml
  - ../base/influxdb.yaml
  - ../base/nextcloud.yaml
  - ../base/hajimari.yaml
patchesStrategicMerge:
  - patch-values.yaml
  - ./unpackerr/patch-values.yaml
