---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  values:
    persistence:
      videos:
        enabled: true
        readOnly: false
        existingClaim: videos-pvc
      videos-archive:
        enabled: true
        readOnly: false
        existingClaim: videos-archive-pvc
      downloads:
        enabled: true
        readOnly: false
        existingClaim: downloads-pvc
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  values:
    persistence:
      videos:
        enabled: true
        readOnly: false
        existingClaim: videos-pvc
      videos-archive:
        enabled: true
        readOnly: false
        existingClaim: videos-archive-pvc
      downloads:
        enabled: true
        readOnly: false
        existingClaim: downloads-pvc
      test:
        enabled: true
        type: hostPath
        hostPath: /rocketpool/kube/pvs/test
        hostPathType: DirectoryOrCreate
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plexmediaserver
  namespace: default
spec:
  values:
    resources:
      requests:
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    podSecurityContext:
      supplementalGroups: [44, 109] # Extra groups for access to hardware encode/decode
    env:
      ADVERTISE_IP: https://plex.${cluster_ext_domain}/
    persistence:
      videos:
        enabled: true
        readOnly: true
        existingClaim: videos-pvc
      videos-archive:
        enabled: true
        readOnly: true
        existingClaim: videos-archive-pvc
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_plex}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: default
spec:
  values:
    persistence:
      downloads:
        enabled: true
        readOnly: false
        existingClaim: downloads-pvc
        mountPath: /datapool/downloads
    service:
      daemon:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_deluge}
        ports:
          torrents:
            enabled: true
            port: 55066
            targetPort: 55066
            protocol: TCP
          admin:
            enabled: true
            port: 58846
            targetPort: 58846
            protocol: TCP
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: default
spec:
  values:
    persistence:
      videos:
        enabled: true
        readOnly: false
        existingClaim: videos-pvc
      videos-archive:
        enabled: true
        readOnly: false
        existingClaim: videos-archive-pvc
    service:
      main:
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_syncthing}
        enabled: true
        externalTrafficPolicy: Local
        type: LoadBalancer
        ports:
          sync:
            enabled: true
            port: 22000
            protocol: TCP
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-controller
  namespace: default
spec:
  values:
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_unifi}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: default
spec:
  values:
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_mqtt}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: default
spec:
  values:
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_influx}
