---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plexmediaserver
  namespace: default
spec:
  values:
    resources:
      requests:
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
      kubernetes.io/hostname: gammatron
    podSecurityContext:
      supplementalGroups: [44, 109] # Extra groups for access to hardware encode/decode
    persistence:
      videos:
        enabled: true
        readOnly: true
        existingClaim: videos-pvc
      config:
        existingClaim: plexmediaserver-config
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_plex}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: default
spec:
  values:
    nodeSelector:
      kubernetes.io/hostname: gammatron
    persistence:
      downloads:
        enabled: true
        readOnly: false
        existingClaim: downloads-pvc
        mountPath: /datapool/downloads
      config:
        existingClaim: deluge-config
    service:
      daemon:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_deluge}
        ports:
          torrents:
            enabled: true
            port: 55066
            targetPort: 55066
            protocol: TCP
          admin:
            enabled: true
            port: 58846
            targetPort: 58846
            protocol: TCP
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: default
spec:
  values:
    nodeSelector:
      kubernetes.io/hostname: gammatron
    persistence:
      videos:
        enabled: true
        readOnly: false
        existingClaim: videos-pvc
      config:
        existingClaim: syncthing-config
    service:
      main:
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_syncthing}
        enabled: true
        externalTrafficPolicy: Local
        type: LoadBalancer
        ports:
          sync:
            enabled: true
            port: 22000
            protocol: TCP
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: default
spec:
  values:
    nodeSelector:
      kubernetes.io/hostname: gammatron
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_influx}
    persistence:
      influxdata:
        existingClaim: influxdb-influxdata
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: default
spec:
  values:
    nodeSelector:
      kubernetes.io/hostname: gammatron
    persistence:
      config:
        existingClaim: prowlarr-config
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ombi
  namespace: default
spec:
  values:
    nodeSelector:
      kubernetes.io/hostname: gammatron
    persistence:
      config:
        existingClaim: ombi-config
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
spec:
  values:
    nodeSelector:
      kubernetes.io/hostname: gammatron
    persistence:
      config:
        existingClaim: tautulli-config
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  values:
    persistence:
      existingClaim: grafana-config
