---
# PLex Production Patch
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plexmediaserver
  namespace: default
spec:
  values:
    persistence:
      videos:
        enabled: true
        readOnly: true
        existingClaim: videos-pvc
      videos-archive:
        enabled: true
        readOnly: true
        existingClaim: videos-archive-pvc
