---
# PLex Production Patch
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plexmediaserver
  namespace: default
spec:
  values:
    env:
      ADVERTISE_IP: https://plex.${cluster_ext_domain}/
    runtimeClassName: nvidia-gpu
    persistence:
      videos:
        enabled: true
        readOnly: true
        existingClaim: videos-pvc
      videos-archive:
        enabled: true
        readOnly: true
        existingClaim: videos-archive-pvc
      config:
        enabled: true
        existingClaim: plex-config-pvc
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_plex}
    resources:
      limits:
        # NOTE: This request only works with a single node cluster
        #   would need node affinity and feature detection to work
        #   and schedule the pods correctly if we had a mixed cluster
        nvidia.com/gpu: 1
        memory: 6000Mi
