---
# PLex Production Patch
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plexmediaserver
  namespace: default
spec:
  values:
    persistence:
      videos:
        enabled: true
        readOnly: true
        existingClaim: videos-pvc
      videos-archive:
        enabled: true
        readOnly: true
        existingClaim: videos-archive-pvc
      config:
        enabled: true
        existingClaim: plex-config-pvc
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_plex}
        ports:
          http:
            enabled: true
            port: 32400
            targetPort: 32400
            protocol: TCP
