# Prod Gammasite PVS
---
# Plex Static Path on dedicated ZFS dataset due to size
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-plex-config-pv
  namespace: default
spec:
  storageClassName: local-datapool
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/datapool/kube/plexmediaserver"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
