---
# Radarr Production Patch
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  values:
    persistence:
      videos:
        enabled: true
        readOnly: false
        type: nfs
        server: ${nfs_provisioner_server}
        path: /datapool/videos
      videos-archive:
        enabled: true
        readOnly: false
        type: nfs
        server: ${nfs_provisioner_server}
        path: /datapool/videos_archive
      downloads:
        enabled: true
        readOnly: false
        type: nfs
        server: ${nfs_provisioner_server}
        path: /datapool/downloads
