---
# Radarr Production Patch
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  values:
    persistence:
      videos:
        enabled: true
        readOnly: false
        existingClaim: videos-pvc
      videos-archive:
        enabled: true
        readOnly: false
        existingClaim: videos-archive-pvc
      downloads:
        enabled: true
        readOnly: false
        existingClaim: downloads-pvc
