---
# Sonarr Production iSCSI Patch
# NOTE: This is using manually created iSCSI LUNs/Targets
# The setup is opting for performance over flexibility due to
# the SQLite Database in the 'arr apps
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  values:
    persistence:
      videos:
        enabled: true
        readOnly: false
        existingClaim: videos-pvc
      videos-archive:
        enabled: true
        readOnly: false
        existingClaim: videos-archive-pvc
      downloads:
        enabled: true
        readOnly: false
        existingClaim: downloads-pvc
