---
# Storage and Networking patches for Syncthing
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: default
spec:
  values:
    persistence:
      videos:
        enabled: true
        readOnly: false
        existingClaim: videos-pvc
      videos-archive:
        enabled: true
        readOnly: false
        existingClaim: videos-archive-pvc
    service:
      syncthing:
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_syncthing}
