---
# Tautulli Production Local Storage Patch - Gammasite Prod single-node
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
spec:
  values:
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 10G
        storageClass: local-path
