---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: default
spec:
  values:
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_homeassistant}
    persistence:
      config:
        existingClaim: homeassistant-config
        type: null
        accessMode: null
        size: null
