apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/testsite
  dependsOn:
    - name: infrastructure
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # Flux Sync Settings
  interval: 30m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
  # Site-specific variables
  postBuild:
    substitute:
      cluster_int_domain: testsite.glenside.lan
      cluster_ext_domain: testsite.garvbox.net
      default_provisioner_scname: local-path
