---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/testsite/infra-base
  dependsOn:
    - name: infra-core-install
  # Enable Encryption using sops-gpg secret pre-loaded with ansible
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
  # Site-specific variables
  postBuild:
    substitute:
      metallb_ip_dns: 192.168.0.46
      metallb_ip_range: 192.168.0.70-192.168.0.80
      metallb_ip_nginx: 192.168.0.70
      cluster_name: testsite
      cluster_ext_domain: testsite.garvbox.net
      cluster_int_domain: ktest.gammasite.lan
      default_provisioner_scname: local-path
      admin_email: support@garvbox.net
