apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/testsite
  dependsOn:
    - name: infra-core-install
  # Enable Encryption using sops-gpg secret pre-loaded with ansible
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
  # Site-specific variables
  postBuild:
    substitute:
      metallb_ip_range: 192.168.0.70-192.168.0.79
      metallb_ip_traefik: 192.168.0.76
      metallb_ip_dns: 192.168.0.75
      cluster_ext_domain: testsite.garvbox.net
      cluster_int_domain: testsite.glenside.lan
      default_provisioner_scname: local-path
      admin_email: gonarvib@protonmail.com
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-core-install
  namespace: flux-system
spec:
  path: ./infrastructure/core-install
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
