---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-controller
  namespace: default
spec:
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: gammatron
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_unifi}
    persistence:
      config:
        existingClaim: unifi-controller-config
        type: null
        accessMode: null
        size: null
