---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-controller-config-pv
  namespace: default
spec:
  storageClassName: local-rocketpool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/unifi-controller-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-rocketpool
  volumeName: unifi-controller-config-pv
  resources:
    requests:
      storage: 1Mi
