---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: kube-system
spec:
  acme:
    email: ${admin_email}
    server: ${le_url:=https://acme-staging-v02.api.letsencrypt.org/directory}
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      dns01:
        cloudflare:
          email: ${admin_email}
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
