---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  values:
    persistence:
      config:
        existingClaim: jellyfin-config
        type: null
        accessMode: null
        size: null
      videos:
        existingClaim: videos-pvc
        type: null
        accessMode: null
        size: null
      archivetvshows:
        existingClaim: archivetvshows-pvc
        type: null
        accessMode: null
        size: null
      archivemovies:
        existingClaim: archivemovies-pvc
        type: null
        accessMode: null
        size: null
      archivesports:
        existingClaim: archivesports-pvc
        type: null
        accessMode: null
        size: null
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_jellyfin}
