apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/alphasite-test
  dependsOn:
    - name: metallb-install
    - name: traefik-install
  # Enable Encryption using sops-gpg secret pre-loaded with ansible
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
  # Site-specific variables
  postBuild:
    substitute:
      metallb_ip_dns: 10.0.40.1
      metallb_ip_range: 10.0.40.2-10.0.40.50
      # Note Traefik IP should be inside the metallb dynamic ip range
      metallb_ip_traefik: 10.0.40.10
      cluster_ext_domain: alphasite-test.garvbox.net
      cluster_int_domain: alphasite-test.glenside.lan
      nfs_provisioner_scname: nfs-kraken
      nfs_provisioner_server: kraken.glenside.lan
      nfs_provisioner_path: /export/alphasite-test
      admin_email: gonarvib@protonmail.com
      # Uncomment to switch to PROD LetsEncrypt URL
      # le_url: https://acme-v02.api.letsencrypt.org/directory
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-install
  namespace: flux-system
spec:
  path: ./infrastructure/base/metallb-install
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-install
  namespace: flux-system
spec:
  path: ./infrastructure/base/traefik-install
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
