apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: kube-system
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:tjnGTIMuJKeV0jw08JyIU8WlW0z7OCemLOLQet31XDyhvNL3jW5wTcejhnk3wnC6meTGABKsbg8=,iv:hJ1V2FWWTJna46tgkfqn2N0ky4qk7ryUB3ahnAd8f38=,tag:OcupPQTIi/POGGhAIuhZsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-16T23:52:25Z"
    mac: ENC[AES256_GCM,data:masM54uJm63Z3LtT4NXNHznVto9f0NK0eODKLbMOj6oJslp45oZfWdz1dIllixIyxkeGdNfPOc5eE2j2m6jypALBZiF20YWUTuJuKR1yHkl8L/Il7qHr465mg6KCuMJ3buF1nEqLdc6ra74DRggn4P0EGkbKdNR2nG5Br3qt22Q=,iv:7qZ5Bqjdn8o7ZFdoJf7ZIedFK4493fvkJX/E21D+a9A=,tag:Xrq2MSpbXT824Lx9l20oFw==,type:str]
    pgp:
        - created_at: "2022-05-16T23:52:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+dCYlBvkIYeAQ/6A+C6pgcMT1nROji4ZRfmuvIFioctZLL5ajxQavAkyRKd
            1xPSCFph1GZt+0fYZdVSbNPeV5vLW1rsJSxFUacY9W/V6L4tOkOTnL+s04UFUzrK
            Y742GkDf7cubr2EPpviE9NVVBH4zX9jbOwzMvU/X+eQC1H9Puibz98RwuhRE2ja8
            pmjxu+HlVCgibP2G93D8sPXSt+D5mDAEqKQCnZdWtU+kwnpNViDFAZPYIGS/6XqG
            dWbU9SE2GKBuonpm8r6VTd5OiQS8MITqw1gbuZCusqaE53m/INyFed6E6AnGsLI8
            eI4jiWGVj6Tobu98axBq2uFtBvoRhsqNhDSdLSuau269xNjaafJBSl2Q2dkzSbo4
            6D836X4TIk86OJH/c7Q8hShpdYJtjSrboQGe89FM95BDgTPnfXH26m8sEZMxAVCZ
            kroNSOKaMDWNem8M8VBtl36C4lCrLaiD6rXuk0rurz1JhJ6xUJTQxC5pQZsTkbI9
            RCqfsSXrPgUNiDIpL86bNP83St0KiDK9NsXL/jvY0Ds7Q18Z9kLmSEglKFJzdBTA
            pNsn9m+tNwXPg/Kr1+OGrCnPj9vyLlhEBVFZieQIWzYyJHS7XkE+ybEga0Fl4pXJ
            FKgYg2nZlASVXOLtwKbd7eao2T/zMjEr9WtO/bOcgnmSTaW4P7m145RQCU8Nr73S
            XAFN3Hwiuy1jPAPl1YV/VXIPe4CAD213rK7Z7+jGoFq49OyZ4z4NvaZ73yXIE30N
            TOxw4zhQV3YlA3CRohC3HAeKcFCI3540xxssJ7GAfbV83l2BBcPnEtAuIFa5
            =31D/
            -----END PGP MESSAGE-----
          fp: 198D28ED83032B0109E7000370C125831285948D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
