apiVersion: v1
kind: Secret
metadata:
    name: discord-url
    namespace: flux-system
data:
    address: ENC[AES256_GCM,data:8W3KcGMuV7XO5iZnQr3gnLYyGeaXpdIDudJoQenZvoc3HisvLIwH1rqw5o1eHrxUC8uSlJpPwm+7EKzyJTIbDBnNy2Qaoy3AJLeN/mE4XXLJmCvqsF69azUv9icYsEd2MxTlP4bwemIYm7YBazqsPoEiydRk/78/k7kKgKvovPMOFrcwDtXCe4PQCvdpXkKUa6zzoolnydRY3yR+RH669g==,iv:MpO/6x8pXIr9OyiwctZvx4O0tDukDsmKVmX3sE/mJN8=,tag:wCBDY1EmRFzLR4mkG5lzXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-16T22:15:47Z"
    mac: ENC[AES256_GCM,data:fJ9Aq7CzWFxDbD2t/pqUNkPKDSKSaIMNDEvtcCmefmu/8MKClsh6l/9TdCCWG7rmU1g+VRpcvx5CMUKBJT/JAyLFk/eUgo9PFKT4G4haTeyfZKH6M0VvjiRYVaqM/tQU4L0MtdBR3drOpA6/XlVgnsnLQHb0lME38ie6DE3TpBY=,iv:wFc7NknEGWfdahxtdkhiux6h4emeCb2oIpoLi9BUPEA=,tag:z01Vdqpwhxv51PnwK02coQ==,type:str]
    pgp:
        - created_at: "2022-05-16T22:15:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA+dCYlBvkIYeAQ//VjBrsOzLrgpPhIGo6pGlnlox3qcbpp61sheIdqULnwrh
            P9nbQHaTGSjKJ53o++2qxfb8drxbmuNgtFf2JCXFMjib6CgqBfgcBstw1+Gdf9jc
            8l4X2eXXIbe3YpSu8fqS3vzfoTUJ5Hly1Lj0RIO7GV59dhM+/8D6aKJ3a1xtgRcm
            CEkg5BandImu7HF2v8JVeyi3XvkHfVX5iI0NhO8tWqrQjOPwXC15DSSI+RvJJL3I
            1Wslnix58LX+jWfwfzpBuY9QagX1xkmQP2DnH04iJxBu4s8C9AhY4VnhmkT6PDDo
            3Ew092UkusAnEA2qWlcOlIqQE7Ar8VIMf1gaPQQR2OPTR4JU9n7R5Kei1tNz19KK
            X2Q/Fho7AEWTO8+L3J9lFNwjjWu0Hw+ZcQkzTPRbI49r/fLrkGpI4NFBdL+eTWGr
            llQngZ3d9TU8mrZkwobGqMG1P7ptnR4evSK25L9NL8zewFWS6r+tAbttyRpOLI2j
            hK5yl23eh8wTF1taixdTt7CC2eR8+451Cr1FahaaqT7EjUM6utMlNI0fetNg+vMf
            Cia01OyvsGJEIJPPbv0tKItdV6u4zpDLB3s9XVt9na4Wjzz9MtOjLHhohEWRpOIJ
            WNhsDXudB2+t0Zaq6viP76E5Zzcm5H7pgvvBKBYzz/ykwBg37mSVpkdKcRqUCPTS
            XgFki+yOaWc1ZgYs9L4w6ZNdMOKmEKaRKCrq5UtDn9mQKuWL8ujTBgS8O87ChqBT
            5o2qfpMCaA5mF/0yh3MrrzHR2YYom7lHqWldChzADqVREceq7FVyphVw/n0kUd0=
            =gCky
            -----END PGP MESSAGE-----
          fp: 198D28ED83032B0109E7000370C125831285948D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
