# Apply DNS config for external queries
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  external.server: |
    ${cluster_ext_domain}:53 {
      kubernetes
      k8s_external ${cluster_ext_domain}
    }
