---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    configInline:
      address-pools:
        - name: reserved # Reserved single IP for DNS
          protocol: layer2
          auto-assign: false
          addresses:
            - ${metallb_ip_dns}/32
        - name: default
          protocol: layer2
          addresses:
            - ${metallb_ip_range}
