---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner-charts
        namespace: flux-system
  values:
    storageClass:
      name: ${nfs_provisioner_scname}
    nfs:
      server: ${nfs_provisioner_server}
      path: ${nfs_provisioner_path}
