apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-helm-chart
  namespace: flux-system
spec:
  interval: 5m
  path: "./traefik/helmrelease.yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-tlsstore
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-helm-chart
  interval: 5m
  path: "./traefik/tlsstore.yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
