---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: default
spec:
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: gammatron
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_influx}
    persistence:
      influxdata:
        existingClaim: influxdb-influxdata
        type: null
        accessMode: null
        size: null
