---
# Unpackerr Production Secret Patch
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: unpackerr
  namespace: default
spec:
  values:
    persistence:
      downloads:
        enabled: true
        readOnly: false
        existingClaim: downloads-pvc
      unpackerr-config:
        enabled: true
        name: unpackerr-config
        type: secret
        globalMounts:
          - path: /config/unpackerr.conf
            subPath: unpackerr.conf
