---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Any site-specific configs/patches should be loaded here before loading the base config
resources:
  - ./discord-secrets.yaml
  - ./cf-secret.yaml
  - ./videos-pvs.yaml
  - ./config-pv.yaml
  - ../base
  - ../base/nvidia-device-plugin
