# Static Video PVCs using local storage
---
# Datapool Videos
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-videos-pv
  namespace: default
spec:
  storageClassName: local-datapool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/datapool/videos"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-datapool
  volumeName: local-videos-pv
  resources:
    requests:
      storage: 1Mi
---
# Datapool Videos Archive
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-videos-archive-pv
  namespace: default
spec:
  storageClassName: local-datapool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/datapool/videos_archive"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos-archive-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-datapool
  volumeName: local-videos-archive-pv
  resources:
    requests:
      storage: 1Mi

---
# Datapool Downloads
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-downloads-pv
  namespace: default
spec:
  storageClassName: local-datapool
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/datapool/downloads"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gammatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-datapool
  volumeName: local-downloads-pv
  resources:
    requests:
      storage: 1Mi
