apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Any site-specific configs/patches should be loaded here before loading the base config
resources:
  - helmrelease.yaml
  - tlsstore.yaml
