# Add Local IP Restriction
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: localonly
  namespace: default
spec:
  ipWhiteList:
    sourceRange:
      - 127.0.0.1/32
      - 192.168.0.0/16
      - 10.0.0.0/8
