---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: default
spec:
  values:
    env:
      PGADMIN_DEFAULT_EMAIL:
        valueFrom:
          secretKeyRef:
            name: pgadmin-secret
            key: username
