---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.13.3
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: metallb-system
