---
# Deluge Production Storage and Service Patches
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: default
spec:
  values:
    persistence:
      videos:
        enabled: true
        readOnly: false
        existingClaim: nfs-videos-pvc
        mountPath: /datapool/videos
      downloads:
        enabled: true
        readOnly: false
        existingClaim: nfs-downloads-pvc
        mountPath: /datapool/downloads
