---
# Gitea Production DB Patch
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  valuesFrom:
  - kind: Secret
    name: gitea-db-pass
    targetPath: gitea.config.database.PASSWD
    valuesKey: PASSWD
  values:
    postgresql:
      enabled: false
    gitea:
      config:
        database:
          DB_TYPE: postgres
          USER: gitea
          HOST: databox-pg.glenside.lan:5432
          NAME: gitea_prod