---
# Radarr Production iSCSI Patch
# NOTE: This is using manually created iSCSI LUNs/Targets
# The setup is opting for performance over flexibility due to
# the SQLite Database in the 'arr apps
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  values:
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10G
        type: custom
        volumeSpec:
          iscsi:
            targetPortal: 10.0.20.5:3260
            iqn: iqn.2022-06.lan.glenside.kraken:alphasite-prod-radarr
            lun: 1
            fsType: ext4
      videos:
        enabled: true
        readOnly: false
        existingClaim: nfs-videos-pvc
      videos-archive:
        enabled: true
        readOnly: false
        existingClaim: nfs-videos-archive-pvc
      downloads:
        enabled: true
        readOnly: false
        existingClaim: nfs-downloads-pvc