# Gitea PostGres Secret
apiVersion: v1
kind: Secret
metadata:
    name: gitea-db-pass
    namespace: default
data:
    PASSWD: ENC[AES256_GCM,data:r3/OVg6fIYSU4l3Po557QA==,iv:EUkVrXBuoHBkUEhORfGPJQdf+InoMat3ljseKCvWXA0=,tag:lbecWivrQLhTtPhI5PlXhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-11T16:25:06Z"
    mac: ENC[AES256_GCM,data:pJma0AZiJVhKhgzhgp93SlBZyacEV25qr5QNmz8n/CcvQ2Yx9aL+p3he5LncYxG7WJOgkikTko1HhpdZlqZlRFyLqhSDG7ob525h5u7z1IyI88ZEAjKcFo3b3k+IECs10BHx8k4Tt4BUrRbSqu9E+3pCGMZuNorne7WkrX+p0n0=,iv:XQKK4bAo4MnehzMGlydtwJYGwBj8z9IB31m5hfzELwU=,tag:EOmDdDMdN6SwGeS7ARB6xg==,type:str]
    pgp:
        - created_at: "2022-06-11T16:25:06Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7A1ru9tuH/BARAAluQ60fanqmt7FOJ617IUiwd13In+Px+5vyW+EM4R9m97
            Vr3eFNqH0uHal4Bk19VmTw2pPhtjXExy9e9UxcpCVltR9GbYt/ny79WBT/aMghpU
            p1G2k0N1oRBrDag+ZGU8kyspV7C1Yz5hwgclyP8R44bAcjHgOjZ4kMtZm0aBUN/Z
            THKnwqQ16O97s9tMctvMZKNke/ykBuvUZtwDiNnTnwMqX1RLpU3xfwsAWh526qwQ
            /30uHCyC+9mBCQz4TXz+6x8A9dFiYah5yiMlmHQZsYPnkhXn3n7UJfWlJAWlKqIY
            hJc9Fi47KM/uLKiXllXyprU/Q9pQVEdAnDVOZrglRoxqVH2vFeEfPiNGrxyXNfVJ
            cFQh3A/KdckPJaLBsMoP+p0pifr546PyYsVHDhkNa7QWCd/yR29tEIWROCACqfuX
            ulmABWdOjPdaKT6f0Xegb/iVZ/mn4QzwGs9S7Nf8dFrSCDMrZNpRKGkNxfDLqWQX
            nEm+BaWiv3AtugZR+M+2yFy266GyjHoPrx9vBqFU3jZ9DBgqpT3s2EtrnuYNRK3w
            uyem5UVzC0b6kmcVJMHdQTDK0xYe53gVml92WgMGr7fyZhjHKG1Q2nUS593QxqRP
            QG8ieIJRxXZNI3oVL8o0GInUwcfqH4lXoApTheVaFiwBinpk4Czu4LJ9ShyG+d/S
            XgG5OBrXRxTLEkTtnpjrJZ9LCLvDJmbAb3pCD0ZbwaIZQgirnt4w9Cz1W6PILm+K
            OmGDfAUfC29O95ZnHx9VrZIQ9JS4ff5Zm2axwld+si3N/4S8fm8TFCJ99VzIvG8=
            =hjT8
            -----END PGP MESSAGE-----
          fp: BCFD0656354D49F51B8C16148A18DAD76BC16DB2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
