---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 10.32.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    # Values taken from example:
    #   https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
    # Removed some unused values

    image:
      name: traefik
      tag: v2.8.8
      repository: traefik # Added repo for renovate to detect version

    # Disable silly traefik ingressroute
    ingressRoute:
      dashboard:
        enabled: false

    # Configure Traefik static configuration
    # Additional arguments to be passed at Traefik's binary
    # All available options available on https://docs.traefik.io/reference/static-configuration/cli/
    ## Use curly braces to pass values: `helm install --set="additionalArguments={--providers.kubernetesingress.ingressclass=traefik-internal,--log.level=DEBUG}"`
    additionalArguments: []
    env: []
    ports:
      # The name of this one can't be changed as it is used for the readiness and
      # liveness probes, but you can adjust its config to your liking
      traefik:
        port: 9000
        expose: false
        exposedPort: 9000
        protocol: TCP
      web:
        port: 8000
        expose: true
        exposedPort: 80
        protocol: TCP
        redirectTo: websecure
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: false
          options: ""
          certResolver: ""
          domains: []
      metrics:
        port: 9100
        expose: false
        exposedPort: 9100
        protocol: TCP

    # Options for the main traefik service, where the entrypoints traffic comes
    # from.
    service:
      # Disabled - we use our own defined service
      enabled: false
