# Apply DNS config for external queries
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  external.server: |
    alphasite-test.glenside.lan:53 {
      kubernetes
      k8s_external alphasite-test.glenside.lan
    }
