---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.15
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    adminUser:
      create: true
      username: admin
      passwordHash: "$2a$10$P/tHQ1DNFXdvX0zRGA8LPeSOyb0JXq9rP3fZ4W8HGTpLV7qHDlWhe"
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: ${wl_source_range}
        hajimari.io/icon: mdi:sawtooth-wave
      hosts:
        - host: gitops.${cluster_ext_domain}
          paths:
            - path: /
              pathType: Prefix
    networkPolicy:
      create: false
    metrics:
      enabled: true
