
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: ">5.0.0"
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts: 
        - host: gitea.${cluster_ext_domain}
          paths:
            - path: "/"
              pathType: Prefix
      tls: []
    persistence:
      enabled: true
      size: 4Gi
      accessModes:
        - ReadWriteOnce
      labels: {}
      annotations: {}
      storageClass: "nfs-kraken"
    postgresql:
      persistence:
        size: 500Mi
        storageClass: "nfs-kraken"
    podSecurityContext: {}  # Disabled security context for NFS data access
      # fsGroup: 1000
    config: {}  #  Gitea Config settings
    service:
      ssh:
        type: LoadBalancer
        port: 22
        # clusterIP: None
        loadBalancerIP:
        annotations:
