---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zoneminder
  namespace: default
spec:
  values:
    controllers:
      main:
        containers:
          main:
            env:
              MYSQL_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: zoneminder-db-secret
                    key: app-password
          db:
            env:
              MYSQL_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: zoneminder-db-secret
                    key: root-password
              MYSQL_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: zoneminder-db-secret
                    key: app-password

