---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zoneminder
  namespace: default
spec:
  values:
    controllers:
      main:
        containers:
          main:
            env:
              - name: MYSQL_USER
                value: zoneminder
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: zoneminder-db-secret
                    key: app-password
          db:
            env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: zoneminder-db-secret
                    key: root-password
              - name: MYSQL_DATABASE
                value: zm
              - name: MYSQL_USER
                value: zoneminder
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: zoneminder-db-secret
                    key: app-password

