---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/deltasite
  dependsOn:
    - name: infrastructure
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
  # Site-specific variables
  postBuild:
    substitute:
      cluster_name: deltasite
      cluster_int_domain: kube.deltasite.lan
      cluster_ext_domain: deltasite.garvbox.net
      default_provisioner_scname: local-path
      wl_source_range: 192.168.0.0/16,10.0.0.0/8
