---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/deltasite/infra-base
  dependsOn:
    - name: infra-core-install
  # Enable Encryption using sops-gpg secret pre-loaded with ansible
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: true
  force: true
  # Site-specific variables
  postBuild:
    substitute:
      metallb_ip_dns: 192.168.3.210
      metallb_ip_range: 192.168.3.211-192.168.3.220
      metallb_ip_nginx: 192.168.3.215
      metallb_ip_frigate: 192.168.3.216
      # These are only used in the apps kustomization but listed here to avoid duplication
      wl_source_range: 192.168.0.0/16,10.0.0.0/8
      cluster_name: deltasite
      cluster_ext_domain: deltasite.garvbox.net
      cluster_int_domain: kube.deltasite.lan
      default_provisioner_scname: local-path
      admin_email: gonarvib@protonmail.com
      le_url: https://acme-v02.api.letsencrypt.org/directory
      host_path_base: /data/kube/pvs
