---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      image:
        registry: registry.k8s.io
        image: ingress-nginx/controller
        tag: v1.4.0
      service:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${metallb_ip_nginx}"
        externalTrafficPolicy: Local
      extraArgs:
        default-ssl-certificate: kube-system/letsencrypt-cert-secret
      ingressClassResource:
        default: true
