---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plexmediaserver
  namespace: default
spec:
  values:
    controllers:
      main:
        containers:
          main:
            resources:
              requests:
                nvidia.com/gpu: 1
              limits:
                nvidia.com/gpu: 1
            env:
              ADVERTISE_IP: "https://${metallb_ip_plex}:32400/"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
    defaultPodOptions:
      securityContext:
        supplementalGroups: [44, 109] # Extra groups for access to hardware encode/decode
      runtimeClassName: nvidia-gpu
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
    persistence:
      config:
        existingClaim: plexmediaserver-config
        type: null
        accessMode: null
        size: null
      transcode:
        type: persistentVolumeClaim
        existingClaim: plexmediaserver-transcode
      videos:
        existingClaim: videos-pvc
      archivetvshows:
        existingClaim: archivetvshows-pvc
      archivemovies:
        existingClaim: archivemovies-pvc
      archivesports:
        existingClaim: archivesports-pvc
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_plex}
