---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plexmediaserver
  namespace: default
spec:
  values:
    controllers:
      main:
        containers:
          main:
            resources:
              requests:
                nvidia.com/gpu: 1
              limits:
                nvidia.com/gpu: 1
            env:
              ADVERTISE_IP: "https://${metallb_ip_plex}:32400/"
    runtimeClassName: nvidia-gpu
    tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
    defaultPodOptions:
      securityContext:
        supplementalGroups: [44, 109] # Extra groups for access to hardware encode/decode
    persistence:
      config:
        existingClaim: plexmediaserver-config
      transcode:
        enabled: true
        existingClaim: plexmediaserver-transcode
      videos:
        enabled: true
        readOnly: true
        existingClaim: videos-pvc
      archivetvshows:
        enabled: true
        readOnly: true
        existingClaim: archivetvshows-pvc
      archivemovies:
        enabled: true
        readOnly: true
        existingClaim: archivemovies-pvc
      archivesports:
        enabled: true
        readOnly: true
        existingClaim: archivesports-pvc
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_plex}
