---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/advplyr/audiobookshelf
      tag: 2.4.0
    env:
      TZ: "Europe/Dublin"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:bookshelf
        hosts:
          - host: audiobookshelf.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 10Gi
      metadata:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 10Gi
      media:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 10Gi
