---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: deluge
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/deluge
      tag: 2.0.5
    probes:
      liveness:
        enabled: false
    env:
      TZ: "Europe/Dublin"
      PUID: "6666"
      PGID: "6666"
      DELUGE_LOGLEVEL: "info"
    # podSecurityContext:
    #   runAsUser: 6666
    #   runAsGroup: 6666
    #   fsGroup: 6666
    #   fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: deluge.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
        tls: []
    persistence:
      # Note Staging setup only has config vol as empty dir - this is overridden
      # for production with real volumes and share mounts
      config:
        enabled: true
        type: emptyDir
