---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: linuxserver/deluge
      tag: 2.1.1
    env:
      TZ: "Europe/Dublin"
      PUID: "6666"
      PGID: "6666"
      DELUGE_LOGLEVEL: "info"
    service:
      main:
        ports:
          http:
            port: 8112
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16,10.0.0.0/8
        hosts:
          - host: deluge.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: "${default_provisioner_scname}"
        accessMode: ReadWriteOnce
        size: 10Gi
