---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: linuxserver/deluge
      tag: 2.1.1
    env:
      TZ: "Europe/Dublin"
      PUID: "6666"
      PGID: "6666"
      DELUGE_LOGLEVEL: "info"
    service:
      main:
        ports:
          http:
            port: 8112
      torrents:
        enabled: true
        ports:
          torrent:
            enabled: true
            port: 55066
            targetPort: 55066
            protocol: TCP
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: deluge.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
        tls: []
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: "${default_provisioner_scname}"
        accessMode: ReadWriteOnce
        size: 10Gi
