---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: factorio-server
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: factoriotools/factorio
      tag: 1.1.73
    env:
      TZ: "Europe/Dublin"
      LOAD_LATEST_SAVE: true
      UPDATE_MODS_ON_START: true
    service:
      main:
        enabled: true
        type: LoadBalancer
        ports:
          http:
            enabled: false
            primary: false
          factorio:
            enabled: true
            primary: true
            port: 34197
            protocol: UDP
          rcon:
            enabled: true
            port: 27015
            protocol: TCP
    podSecurityContext:
      runAsUser: 845
      runAsGroup: 845
      fsGroup: 845
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      factorio:
        enabled: true
        type: pvc
        storageClass: "${default_provisioner_scname}"
        accessMode: ReadWriteOnce
        size: 10Gi
