---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: frigate
      version: 7.4.0
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: 0.13.2
    config: |
      mqtt:
        enabled: False
      cameras:
        dummy_camera: # <--- this will be changed to your actual camera later
          enabled: False
          ffmpeg:
            inputs:
              - path: rtsp://127.0.0.1:554/rtsp
                roles:
                  - detect
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/icon: mdi:cctv
        nginx.ingress.kubernetes.io/whitelist-source-range: ${wl_source_range}
      hosts:
        - host: frigate.${cluster_ext_domain}
          paths:
            - '/'
    persistence:
      config:
        enabled: true
        size: 1Gi
      media:
        enabled: true
        size: 25Gi
