
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: ">5.0.0"
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
  valuesFrom:
  - kind: Secret
    name: gitea-db-pass
    targetPath: gitea.config.database.PASSWD
    valuesKey: PASSWD
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts: 
        - host: gitea.${cluster_ext_domain}
          paths:
            - path: "/"
              pathType: Prefix
      tls: []
    persistence:
      enabled: true
      size: 4Gi
      accessModes:
        - ReadWriteOnce
      labels: {}
      annotations: {}
      storageClass: "${nfs_provisioner_scname}"
    postgresql:
      enabled: false
    gitea:
      config:
        server:
          SSH_DOMAIN: gitea-ssh.default.${cluster_int_domain}
        database:
          DB_TYPE: sqlite3
    service:
      ssh:
        type: LoadBalancer
        # Allow SSH to automatically pull an IP from MetalLB LoadBalancer
        # port: 22
        # clusterIP: None
        # loadBalancerIP:
        # annotations:
