---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.32.9
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    image:
      repository: grafana/grafana
      tag: 9.0.5
    persistence:
      enabled: true
      type: pvc
      storageClass: "${nfs_provisioner_scname}"
      size: 5Gi
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - grafana.${cluster_ext_domain}
      path: "/"
      pathType: Prefix
