---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 6.50.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    image:
      repository: grafana/grafana
      tag: 9.3.2
    persistence:
      enabled: true
      type: pvc
      storageClass: "${default_provisioner_scname}"
      size: 5Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.${cluster_ext_domain}
      path: "/"
      pathType: Prefix
