---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 6.42.3
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    image:
      repository: grafana/grafana
      tag: 9.2.1
    persistence:
      enabled: true
      type: pvc
      storageClass: "${default_provisioner_scname}"
      size: 5Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16,10.0.0.0/8
      hosts:
        - grafana.${cluster_ext_domain}
      path: "/"
      pathType: Prefix
