---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 6.61.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: grafana/grafana
      tag: 10.2.0
    persistence:
      enabled: true
      type: pvc
      size: 5Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.${cluster_ext_domain}
      path: "/"
      pathType: Prefix
      annotations:
        hajimari.io/icon: simple-icons:grafana
