---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: influxdb
              tag: 1.8.10
            env:
              TZ: "Europe/Dublin"
    service:
      main:
        ports:
          http:
            port: 8086
    persistence:
      influxdata:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 25G
        globalMounts:
          - path: /var/lib/influxdb
