---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: jackett
      version: 11.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/jackett
      tag: v0.20.1292
    env:
      TZ: "Europe/Dublin"
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: "${nfs_provisioner_scname}"
        accessMode: ReadWriteOnce
        size: 1Gi
