---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/jackett
      tag: 0.20.2285
    env:
      TZ: "Europe/Dublin"
    service:
      main:
        ports:
          http:
            port: 9117
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: "${default_provisioner_scname}"
        accessMode: ReadWriteOnce
        size: 1Gi
