---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kerberos
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: kerberos/agent
              tag: b67a72b
            env:
              TZ: "Europe/Dublin"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
        initContainers:
          download-config:
            image:
              repository: kerberos/agent
              tag: b67a72b
            command:
              [
                "cp",
                "/home/agent/data/config.template.json",
                "/home/agent/data/config/config.json",
              ]
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          hajimari.io/icon: mdi:cctv
          nginx.ingress.kubernetes.io/whitelist-source-range: ${wl_source_range}
        hosts:
          - host: kerberos.${cluster_ext_domain}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    persistence:
      kerberos-data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        advancedMounts:
          main: 
            main: 
              - path: /home/agent/data/config
                subPath: config
                readOnly: false
              - path: /home/agent/data/recordings
                subPath: recordings
                readOnly: false
              - path: /home/agent/data/snapshots
                subPath: snapshots
                readOnly: false
              - path: /home/agent/data/cloud
                subPath: cloud
                readOnly: false
            download-config:
              - path: /home/agent/data/config
                subPath: config
                readOnly: false
