---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 3.5.19
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    nextcloud:
      host: nextcloud.${cluster_ext_domain}
      phpConfigs:
        override_max_file_size.ini: |-
          upload_max_filesize=10G
          post_max_size=10G
    phpClientHttpsFix:
      enabled: true
      protocol: https
    internalDatabase:
      enabled: true
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        hajimari.io/icon: simple-icons:nextcloud
      path: /
      pathType: Prefix
    persistence:
      enabled: true
