---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: dpage/pgadmin4
      tag: 7.8
    env:
      TZ: "Europe/Dublin"
      PGADMIN_DEFAULT_EMAIL: "insecure_default@example.com"
      PGADMIN_DEFAULT_PASSWORD: "!!insecure_default_pass!!"
      PGADMIN_DISABLE_POSTFIX: "1"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: simple-icons:postgresql
          nginx.ingress.kubernetes.io/whitelist-source-range: ${wl_source_range}
        hosts:
          - host: pgadmin.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 10Gi
        mountPath: /var/lib/pgadmin
