---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plexmediaserver
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/plex-beta
      tag: 1.29.2.6364-6d72b0cf6
    probes:
      liveness:
        enabled: false
    env:
      TZ: "Europe/Dublin"
      # ALLOWED_NETWORKS:
      # ADVERTISE_IP:
      # PLEX_CLAIM:
      # PLEX_PREFERENCE_1: "FriendlyName=plex-kubernetes"
      # PLEX_PREFERENCE_2: "EnableIPv6=0"
      # PLEX_PREFERENCE_3: "logDebug=0"
      # PLEX_PREFERENCE_4: "DisableTLSv1_0=1"
      # PLEX_PREFERENCE_5: "LanNetworksBandwidth=xxx.xxx.xxx.0/18\,xxx.xxx.xxx.0/24\,xxx.xxx.xxx.0/24"
      # PLEX_PREFERENCE_6: "TranscoderQuality=2"
      # PLEX_PREFERENCE_7: "TreatWanIpAsLocal=0"
      # PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"
    podSecurityContext:
      runAsUser: 6666
      runAsGroup: 6666
      fsGroup: 6666
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: plex.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
    service:
      main:
        primary: true
        ports:
          http:
            port: 32400
            protocol: TCP
          dlna-tcp:
            port: 32469
            protocol: TCP
            enabled: true
          dlna-udp:
            port: 1900
            protocol: UDP
            enabled: true
          plex-companion:
            port: 3005
            protocol: TCP
            enabled: true
          discovery-udp:
            port: 5353
            protocol: UDP
            enabled: true
          plex-roku:
            port: 8324
            protocol: TCP
            enabled: true
          gdm-32410:
            port: 32410
            protocol: UDP
            enabled: true
          gdm-32412:
            port: 32412
            protocol: UDP
            enabled: true
          gdm-32413:
            port: 32413
            protocol: UDP
            enabled: true
          gdm-32414:
            port: 32414
            protocol: UDP
            enabled: true
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: "${default_provisioner_scname}"
        accessMode: ReadWriteOnce
        size: 10Gi
      transcode:
        enabled: true
        type: emptyDir
