---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plexmediaserver
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/onedr0p/plex-beta
      tag: 1.31.2.6783-9209b39b4
    env:
      TZ: "Europe/Dublin"
      ADVERTISE_IP: "https://plex.${cluster_ext_domain}/"
      # PLEX_CLAIM:
      PLEX_PREFERENCE_1: "LanNetworksBandwidth=192.168.0.0/16,10.0.0.0/16,172.16.0.0/12"
      PLEX_PREFERENCE_2: "TranscoderQuality=0"
      PLEX_PREFERENCE_3: "TranscoderH264BackgroundPreset=fast"
    podSecurityContext:
      runAsUser: 6666
      runAsGroup: 6666
      fsGroup: 6666
      fsGroupChangePolicy: "OnRootMismatch"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:plex
        hosts:
          - host: plex.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
    service:
      main:
        primary: true
        ports:
          http:
            port: 32400
            protocol: TCP
          dlna-tcp:
            port: 32469
            protocol: TCP
            enabled: true
          dlna-udp:
            port: 1900
            protocol: UDP
            enabled: true
          plex-companion:
            port: 3005
            protocol: TCP
            enabled: true
          discovery-udp:
            port: 5353
            protocol: UDP
            enabled: true
          plex-roku:
            port: 8324
            protocol: TCP
            enabled: true
          gdm-32410:
            port: 32410
            protocol: UDP
            enabled: true
          gdm-32412:
            port: 32412
            protocol: UDP
            enabled: true
          gdm-32413:
            port: 32413
            protocol: UDP
            enabled: true
          gdm-32414:
            port: 32414
            protocol: UDP
            enabled: true
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 10Gi
      transcode:
        enabled: true
        type: emptyDir
