---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: ">=16.0.0"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    probes:
      liveness:
        enabled: false
    env:
      TZ: "Europe/Dublin"
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts: 
          - host: radarr.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
        tls: []
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: "${nfs_provisioner_scname}"
        accessMode: ReadWriteOnce
        size: 5Gi
      videos:
        enabled: true
        readOnly: false
        existingClaim: nfs-videos-pvc
      videos-archive:
        enabled: true
        readOnly: false
        existingClaim: nfs-videos-archive-pvc
      downloads:
        enabled: true
        readOnly: false
        existingClaim: nfs-downloads