
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seafile
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: seafile
      version: ">2.0.0"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "Europe/Dublin"
      SEAFILE_SERVER_HOSTNAME: seafile.${cluster_ext_domain}
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts: 
          - host: seafile.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
        tls: []
    persistence:
      data:
        enabled: true
        mountPath: /shared
        type: pvc
        storageClass: "${nfs_provisioner_scname}"
        accessMode: ReadWriteOnce
        size: 5Gi
    mariadb:
      enabled: true
      primary:
        persistence:
          storageClass: "${nfs_provisioner_scname}"
