---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: syncthing/syncthing
      tag: 1.23.0
    probes:
      liveness:
        enabled: false
    env:
      TZ: "Europe/Dublin"
    podSecurityContext:
      runAsUser: 6666
      runAsGroup: 6666
      fsGroup: 6666
      fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        ports:
          http:
            port: 8384
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: syncthing.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: "${default_provisioner_scname}"
        accessMode: ReadWriteOnce
        size: 10Gi
        mountPath: /var/syncthing
