---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/tautulli
      tag: 2.10.4
    env:
      TZ: "Europe/Dublin"
    probes:
      liveness:
        enabled: false
    service:
      main:
        ports:
          http:
            port: 8181
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: tautulli.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
        tls: []
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: "${default_provisioner_scname}"
        accessMode: ReadWriteOnce
        size: 10Gi
