---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-controller
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: lscr.io/linuxserver/unifi-controller
      tag: 7.5.176
    env:
      TZ: "Europe/Dublin"
      MEM_LIMIT: 1024
      MEM_STARTUP: 512
    probes:
      liveness:
        enabled: false
    service:
      main:
        primary: true
        ports:
          http:
            port: 8443
            protocol: TCP
          inform:
            enabled: true
            port: 8080
            protocol: TCP
          ap-disco:
            enabled: true
            port: 10001
            protocol: UDP
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${wl_source_range}
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          hajimari.io/icon: arcticons:unifi-network
        hosts:
          - host: unifi.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 10Gi
