---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-controller
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: lscr.io/linuxserver/unifi-controller
      tag: 7.3.76
    env:
      TZ: "Europe/Dublin"
      MEM_LIMIT: 1024
      MEM_STARTUP: 512
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${metallb_ip_unifi}
        ports:
          http:
            port: 8443
            protocol: TCP
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          ap-disco:
            enabled: true
            port: 10001
            protocol: UDP
          ap-comms:
            enabled: true
            port: 8080
            protocol: TCP
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${wl_source_range}
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        hosts:
          - host: unifi.${cluster_ext_domain}
            paths:
              - path: "/"
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: pvc
        storageClass: "${default_provisioner_scname}"
        accessMode: ReadWriteOnce
        size: 10Gi
