---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: whoami
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: traefik/whoami
              tag: latest
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          hajimari.io/icon: simple-icons:traefikproxy
          nginx.ingress.kubernetes.io/whitelist-source-range: ${wl_source_range}
        hosts:
          - host: whoami.${cluster_ext_domain}
            paths:
              - path: /
                service:
                  name: main
                  port: http
