---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zoneminder
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/zoneminder-containers/zoneminder-base
              tag: 1.36.33
            env:
              TZ: "Europe/Dublin"
              MYSQL_USER: zoneminder
              MYSQL_HOST: zoneminder
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
          db:
            env:
              TZ: "Europe/Dublin"
              MYSQL_USER: zoneminder
              MYSQL_DATABASE: zm
            image:
              repository: mariadb
              tag: 11.6.2
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
          mysql:
            port: 3306
            protocol: TCP
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          hajimari.io/icon: mdi:cctv
          nginx.ingress.kubernetes.io/whitelist-source-range: ${wl_source_range}
        hosts:
          - host: zoneminder.${cluster_ext_domain}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
      log:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
      mysql:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        advancedMounts:
          main:
            db:
              - path: /var/lib/mysql
                readOnly: false
