apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/gammasite-prod
  dependsOn:
    - name: infrastructure
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # Flux Sync Settings
  interval: 60m0s
  timeout: 3m0s
  retryInterval: 2m0s
  wait: true
  prune: false
  force: true
  # Site-specific variables
  postBuild:
    substitute:
      cluster_int_domain: kube.gammasite.lan
      cluster_ext_domain: gammasite.garvbox.net
      default_provisioner_scname: local-path
      metallb_ip_deluge: 192.168.0.61
      metallb_ip_plex: 192.168.0.62
