apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Zr1I6KLGTbihQ3GxDMhH7uJFm4GXZr84h3Kasv1S6yNPT2BJLd+5vw==,iv:orf7VdcHLlpnHlzwA62l1RQGNNusbgT5ioGY3kkzqKM=,tag:JPfgHmzLU09uqe5vwZ1GEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-29T22:00:19Z"
    mac: ENC[AES256_GCM,data:849s6P1b2hJdh39ChTCSotrN2WwdH7HymI/SXpOEGz7sOvhkXZvqcRD0TGzlBK0We/W3Zq93dzTVAP/vL2KW4/Nuefj1JUs9vQzpkc/yZThzvjOlmnS67fj8j91Y133dK7AUemijZ8qKvYB1OaogvoSqAUbUTt1Y2/DTmianu/I=,iv:TqX7WTmwY56P8umRre0u68beiWIck44vY0WLKbqhBFY=,tag:4khmodoqoB7psrkQGYHYpQ==,type:str]
    pgp:
        - created_at: "2022-04-29T22:00:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7A1ru9tuH/BAQ//bahzBOhotWH1p/bDCFPVphpRxh1CFm9FRmY77kAAcbje
            ZqQVzG8M5vrugqcztOu4Xx5G1t80D6AkNuB7PniGqecegSewDQzMfjOGhaiQc0Ms
            0jKnmts6ZxU7vGtTEbPwPNCU0UtuULengg4v0UN1Cqn7kNK2Fxvb4yM1YLxhpMss
            18dhIThcjR39+bLxqVWmprNK1Hl590VHpSn9HEO5YBZveWs+IkV5UAVkvE+a8SZb
            j32vt4WUd2CCIvppPCrVp+4YOxo8fXjixHOrwoZn8AKk0bCKKHBeYmooRW3MsBeQ
            e7agnQt04s2NatB2LmGsMeNhsM4tp/Rzor2v1wllvBxO5TpM+mNDLaBIOQcpkyIN
            uG8bVSXUEEoM3BlTx0SVwgGoXvaULSa0M/9v6JWBe281T4HoxbezntnbqmupyyRW
            Msh5D54M5pYf0zN8BKLoTxP5sYG6wuR04hEj99MlY57WjdO4DoNzBdiPTGh1mPVe
            g4+rWP0cItsUneJQ26rZADFS+i/XMUY5/s+I3pfD2tNP3JE/qGKJrUJVbkxc+3eM
            Mlz/Wg4jZtATuXBKkgiOOs108gfwHppP0667XqoGeDu8AnPir5y9KcgUVwRFY2bD
            bYvLu3JQfrbbSI4Gx7qMBXmI5xM/Yn/yMdM9dVAgsgMEqiqQ7C2gCFQfb2KkSNfS
            XgFbKijuDt4IV4r6pCgyuKSE4DkMNQQCTtfgfPQWkOpojbdJnqq7S4up5lyxYitJ
            gGaHmHPkfhwr9pFrkBb3f5YBOOdXQUmd4Max/1I8KbpI+wYbt4H/tSmpSqTyW5I=
            =g38x
            -----END PGP MESSAGE-----
          fp: BCFD0656354D49F51B8C16148A18DAD76BC16DB2
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
