---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  values:
    persistence:
      config:
        existingClaim: frigate-config
        type: null
        accessMode: null
        size: null
      media:
        existingClaim: frigate-data-pvc
        type: null
        accessMode: null
        size: null
