---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-config-pv
  namespace: default
spec:
  storageClassName: local-ultrapool
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: ${host_path_base}/frigate-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - teslatron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ultrapool
  volumeName: frigate-config-pv
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-frigate-data-pv
  namespace: default
spec:
  storageClassName: nfs-ark
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${nfs_server}
    path: "/mnt/pacific/frigate"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-ark
  volumeName: nfs-frigate-data-pv
  resources:
    requests:
      storage: 1Mi
