name: Lint Yaml

on:
  pull_request:
    branches:
      - main

jobs:
  yamllint:
    name: Check Yaml
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: ibiqlik/action-yamllint@v3
