name: Lint Yaml

on:
  pull_request:
    branches:
      - main

jobs:
  yamllint:
    name: Check Yaml
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: ibiqlik/action-yamllint@v3
