name: Lint Yaml

on:
  pull_request:
    branches:
      - main

jobs:
  yamllint:
    name: Check Yaml
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ibiqlik/action-yamllint@v3
