name: Lint Yaml

on:
  pull_request:
    branches:
      - main

jobs:
  yamllint:
    name: Check Yaml
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: ibiqlik/action-yamllint@v3
